- id: '1540039157597'
  alias: Music Off
  trigger:
  - entity_id: device_tracker.bqaquariusx
    platform: state
    to: not_home
  condition: []
  action:
  - service: media_player.turn_off
    entity_id: all