- id: '1540039157597'
  alias: Music Off
  trigger:
  - entity_id: device_tracker.bqaquariusx
    platform: state
    to: not_home
  condition: []
  action:
  - entity_id: all
    service: media_player.turn_off
  - data: {}
    service: media_player.media_pause