- id: '1540039157597'
  alias: Music Off
  trigger:
  - entity_id: device_tracker.bqaquariusx
    from: home
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: media_player.kuche
    service: media_player.media_pause
  - data:
      entity_id: all
    service: media_player.turn_off
